"""
generate.py — Output generators for DS:R tooling.

Builds BRIEFING.md and SOURCE_INDEX.md from parsed/indexed data.
Both functions return the generated text AND write it to disk.

Public functions:
    briefing()      -> str   writes BRIEFING.md
    source_index()  -> str   writes SOURCE_INDEX.md + source_index.json
"""
import json
import os
from collections import defaultdict
from datetime import date

from . import config
from .parse_md import (
    read_file, parse_bugs, parse_ideas,
    parse_decisions, parse_handoff, parse_build_version
)
from .scan_source import build_full_index


# ── Briefing ──────────────────────────────────────────────────────────────────

def briefing(write=True):
    """
    Generate the session briefing from all project .md files.

    Args:
        write: if True, writes to config.BRIEFING_MD

    Returns:
        Generated markdown string.
    """
    bugs_text      = read_file(config.BUGS_MD)
    ideas_text     = read_file(config.IDEAS_MD)
    decisions_text = read_file(config.DECISIONS_MD)
    handoff_text   = read_file(config.HANDOFF_MD)
    changelog_text = read_file(config.CHANGELOG_MD)

    open_bugs,  staged_bugs             = parse_bugs(bugs_text)
    open_count, planned_count, top_ideas = parse_ideas(ideas_text)
    recent_decisions                     = parse_decisions(decisions_text)
    blockers,   questions                = parse_handoff(handoff_text)
    build_ver                            = parse_build_version(changelog_text)

    lines = [
        f"# DS:R Session Briefing — {date.today()}",
        "*Generated by dsrlib.generate.briefing() — do not edit manually.*\n",
        f"## Current Build: {build_ver}\n",
    ]

    if blockers:
        lines.append("## Blockers (Code queue)")
        for b in blockers:
            lines.append(f"- {b}")
        lines.append("")

    lines.append(f"## Open Bugs ({len(open_bugs)} open, {len(staged_bugs)} need QA)")
    if open_bugs:
        for b in open_bugs:
            lines.append(f"- **{b['id']}** [{b['severity']}] {b['title']}")
    else:
        lines.append("- None")
    if staged_bugs:
        lines.append("\n*Staged — needs Kyle QA:*")
        for b in staged_bugs:
            lines.append(f"- {b['id']}: {b['title']}")
    lines.append("")

    if questions:
        lines.append("## Open Questions for Code")
        for q in questions:
            lines.append(f"- {q}")
        lines.append("")

    lines.append("## Recent Decisions (newest first)")
    for d in recent_decisions:
        lines.append(f"- **{d['id']}** ({d['date']}) — {d['title']}")
    lines.append("")

    lines.append(f"## Ideas Backlog: {open_count} open, {planned_count} planned")
    lines.append("*Most recent open:*")
    for idea in top_ideas:
        lines.append(f"- {idea['id']}: {idea['title']}")
    lines.append("")

    lines += [
        "---",
        "*Detail: BUGS.md · IDEAS.md · DECISIONS.md · CODE_HANDOFF.md*"
    ]

    output = "\n".join(lines)
    if write:
        with open(config.BRIEFING_MD, "w", encoding="utf-8") as f:
            f.write(output)
    return output


# ── Source index ──────────────────────────────────────────────────────────────

def source_index(write=True):
    """
    Generate SOURCE_INDEX.md and source_index.json from the recovered source tree.

    Args:
        write: if True, writes to config.INDEX_MD and config.INDEX_JSON

    Returns:
        (markdown_str, index_dict)
    """
    data    = build_full_index(config.SRC_DIR, config.AREA_DIR)
    present = data["wired_present"]
    missing = data["wired_missing"]
    do_fns  = data["do_functions"]
    gsns    = data["gsn_declarations"]
    areas   = data["area_vnums"]

    present_funcs = {c["function"] for c in present}

    lines = [
        "# DS:R Source Index",
        "*Generated by dsrlib.generate.source_index() — do not edit manually.*\n",
        "## Summary",
        f"- **do_* functions in source:** {len(do_fns)}",
        f"- **Commands wired in interp.c:** {len(data['interp_commands'])}",
        f"  - With implementation: {len(present)}",
        f"  - **Missing implementation: {len(missing)}** "
        f"(may include act_combat.c not yet git-pulled)",
        f"- **gsn_* declarations:** {len(gsns)}",
        f"- **Area files:** {len(areas)}\n",
    ]

    if missing:
        lines += [
            "## Wired Commands Missing Source Implementation",
            "*Commands in interp.c with no matching do_* in workspace.*",
            "*If act_combat.c is not synced from GitHub, those will appear here.*\n",
            "| Command | Expected Function | Trust |",
            "|---------|------------------|-------|",
        ]
        for item in sorted(missing, key=lambda x: x["command"]):
            lines.append(f"| `{item['command']}` | `{item['function']}` | {item['trust']} |")
        lines.append("")

    lines.append("## do_* Function Locations")
    by_file = defaultdict(list)
    for func, info in sorted(do_fns.items()):
        by_file[info["file"]].append((func, info["line"]))
    for fname in sorted(by_file.keys()):
        funcs = sorted(by_file[fname], key=lambda x: x[1])
        lines.append(f"\n### {fname} ({len(funcs)} functions)")
        for func, ln in funcs:
            flag = "" if func in present_funcs else " *(not wired)*"
            lines.append(f"- `{func}` line {ln}{flag}")

    if gsns:
        lines.append("\n## gsn_* Declarations")
        by_file2 = defaultdict(list)
        for gsn, info in sorted(gsns.items()):
            by_file2[info["file"]].append((gsn, info["line"]))
        for fname in sorted(by_file2.keys()):
            entries = sorted(by_file2[fname], key=lambda x: x[1])
            lines.append(f"\n### {fname}")
            for gsn, ln in entries:
                lines.append(f"- `{gsn}` line {ln}")

    lines += [
        "\n## Area Vnum Ranges",
        "| File | Name | Min | Max | Count |",
        "|------|------|-----|-----|-------|",
    ]
    for fname, info in sorted(areas.items()):
        lines.append(
            f"| {fname} | {info['name']} | {info['min_vnum']} "
            f"| {info['max_vnum']} | {info['count']} |"
        )

    lines += ["\n---", "*Regenerate: python3 scripts/index_source.py*"]
    output = "\n".join(lines)

    if write:
        os.makedirs(os.path.dirname(config.INDEX_MD), exist_ok=True)
        with open(config.INDEX_MD, "w", encoding="utf-8") as f:
            f.write(output)
        with open(config.INDEX_JSON, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2)

    return output, data
